### ISSUE TITLE
Add the more detailed documentation

### ISSUE THREAD

**Issue by AntonTrekov** [rubengc/CT#1]
I wanted to test work of a plugin, require ct.php, example.php.
But it can't working with custom database table. I have created table myself and have filled one row, nothing changed. There is no items at the list page. Add new page is empty.

**Comment by rubengc** [comment]
Hi @AntonTrekov 

Thak you so much for your interest on this library, this was initially developed to be used on [GamiPress](https://github.com/rubengc/GamiPress) (and it is in use to store and manage GamiPress logs and user earnings entries)

Let me some time to start a docs section with more documentation about how to setup this library

I also want to integrate the [WP Lib Loader](https://github.com/jtsternberg/wp-lib-loader) by @jtsternberg to ensure load always the latest library version

**Comment by rubengc** [comment]
Closed since at the moment no one is interested on contribute with the documentation
