### ISSUE TITLE
Query updater does not work with multiple `ALTER TABLE` commands. (PROPOSED SOLUTION INCLUDED)

### ISSUE THREAD

**Issue by mholubowski** [rubengc/CT#2]
**Issue**

Query updater does not work with multiple `ALTER TABLE` commands.

For example I added a few columns, removed a couple, renamed a couple and was met with an "almost silent" DB error on the first page refresh. There was a var_dumped db error at the top of the screen, and when I refreshed again it was gone and there were no further attempts by the query updater to reconcile the difference between the actual DB table and the schema definition I was feeding it. 

More details after the proposed solution, at the bottom of this comment.

**Proposed Solution**
Execute each query one at a time in `class-ct-database-schema-updater.php -> run()`

**Before**
```php
                // line 149 class-ct-database-schema-updater.php
                if( ! empty( $sql ) ) {
                    // Execute the SQL
                    $updated = $this->ct_db->db->query( $sql );

                    // Was anything updated?
                    return ! empty( $updated );
                }
```
**After**
```php
                if( ! empty( $sql ) ) {
                    $multiple_sql_queries = explode(';', $sql);
                    // Remove the last element because it's an empty string ($sql will always end in ';')
                    array_pop($multiple_sql_queries); 
                    
                    // Execute each query individually
                    $results = array_map(function($one_sql_query) {
                        return $this->ct_db->db->query( $one_sql_query );
                    }, $multiple_sql_queries);

                    $updated = array_map(function($result) {
                        return ! empty($result);
                    }, $results);
 
                    return in_array(true, $updated);
                }
```

Here is the exact error string that was var_dumped:
WordPress database error: [You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ALTER TABLE wp_solid_affiliate_referrals ADD commission_amount float NOT NULL ; ' at line 1] ALTER TABLE wp_solid_affiliate_referrals DROP COLUMN amount; ALTER TABLE wp_solid_affiliate_referrals ADD commission_amount float NOT NULL ; ALTER TABLE wp_solid_affiliate_referrals ADD order_amount float NOT NULL ; ALTER TABLE wp_solid_affiliate_referrals ADD order_source varchar(255) NOT NULL ;

Here is the query but with formatting, to make it easier to read: 

```sql
ALTER TABLE
  wp_solid_affiliate_referrals DROP COLUMN amount;
ALTER TABLE
  wp_solid_affiliate_referrals
ADD
  commission_amount float NOT NULL;
ALTER TABLE
  wp_solid_affiliate_referrals
ADD
  order_amount float NOT NULL;
ALTER TABLE
  wp_solid_affiliate_referrals
ADD
  order_source varchar(255) NOT NULL;

```

@rubengc I know you're busy, but unless I'm misunderstanding something this seems like a severe issue that could also affect your projects. Would really appreciate if you took a glance at this, and if you have any tests on other projects using CT that would verify edge cases in my proposed solution would be great if you ran them.

**Comment by mholubowski** [comment]
Additional information:

![image](https://user-images.githubusercontent.com/2035619/81213356-185a0400-8f8b-11ea-81bd-9ad135bd9c14.png)

**Comment by rubengc** [comment]
Hi @mholubowski 

Thank you so much for your report and sorry for the delay here

I just did a new commit fixing this issue

Best regards
