### ISSUE TITLE
Bug: Uncaught Error: Call to a member function get_columns() on null in includes/class-ct-list-view.php:243

### ISSUE THREAD

**Issue by MichaelPote** [rubengc/CT#3]
It seems like CT is hooking into ALL screen settings updates without checking which are valid for CT or which should be ignored.

I fixed this error by changing the following:

    public function set_screen_settings( $value_to_set, $option, $value ) {

            global $ct_table, $ct_list_table;

            //INSERTED THE BELOW:
            if (is_null($ct_list_table)) return $value;

**Comment by rubengc** [comment]
Fixed!

Thanks for your report and contribution
