### ISSUE TITLE
Can't set CURRENT_TIMESTAMP as a default value for datetime columns

### ISSUE THREAD

**Issue by etraininteractive** [rubengc/CT#4]
When you setup schema for a datetime field, you should be able to use CURRENT_TIMESTAMP as a value. 

https://dev.mysql.com/doc/refman/5.6/en/data-type-defaults.html

Currently, this declaration gets wrapped in quote marks, and is deemed invalid by MySQL.

Obviously since we define it in a PHP array, it'll need to be initially parsed in quote marks to be valid in php, so this string will need to be caught when defining the schema and not considered a string and wrapped in quote marks when being formatted for SQL.

**Comment by rubengc** [comment]
Hi @etraininteractive 

Thank you so much for report this issue!

I just added it to our roadmap to fix this issue as soon as possible

Best regards
