### ISSUE TITLE
Can't add UNIQUE_KEY combinations to schema

### ISSUE THREAD

**Issue by etraininteractive** [rubengc/CT#5]
We have a user_id and post_id column. For our purposes, there can never be more than one row for each user_id and post_id combination in the database. 

The following UNIQUE_KEY declaration would ensure this:

`UNIQUE KEY unique_user_post (user_id, post_id)`

However, using the CT schema creator, this is not possible. Even if I manually enter the schema as a string, this line is stripped.

**Comment by rubengc** [comment]
Hi @etraininteractive 

Thank you so much for your suggestion!

I just added it to our roadmap to fix this issue as soon as possible

Best regards
