### ISSUE TITLE
Syntax error when attempting to define the PRIMARY KEY when custom entering schema

### ISSUE THREAD

**Issue by etraininteractive** [rubengc/CT#6]
In ct_register_table(), entering the schema in as a string instead of an array does not correctly define the PRIMARY KEY.

For example, if I define the PRIMARY KEY as PRIMARY KEY  (ID), it strips the value 'ID' and leaves it blank as  PRIMARY KEY  (), resulting in a SQL syntax error.

Eg.

`"schema" => "
ID BIGINT(20) NOT NULL AUTO_INCREMENT, 
post_id BIGINT(20) NOT NULL , 
user_id BIGINT(20) NOT NULL , 
role VARCHAR(60) NOT NULL DEFAULT 'member' , 
date_added DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , 
PRIMARY KEY  (ID)"`

This will result in:

`ID BIGINT(20) NOT NULL AUTO_INCREMENT, 
post_id BIGINT(20) NOT NULL , 
user_id BIGINT(20) NOT NULL , 
role VARCHAR(60) NOT NULL DEFAULT 'member' , 
date_added DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , 
PRIMARY KEY  ()`

**Comment by rubengc** [comment]
Hi @etraininteractive 

Thank you so much for your report this issue!

I just added it to our roadmap to fix this issue as soon as possible

Best regards
