### ISSUE TITLE
Maybe migrate this to a class autoloader and namespaces combination ?

### ISSUE THREAD

**Issue by andreigazez** [rubengc/CT#7]
Would have been much more easier to be included in projects using autoloader and namespaces instead of wp lib loader hackish approach. Also you could consider not having any functions outside the classes like the ones from the /includes/functions.php.

Love your work with this class, makes it so easier to use WP_List_Table, but probably it's still a work in progress.

**Comment by rubengc** [comment]
Hi @avbuga 

Thank you so much for your suggestion we will keep it in mind for future updates!
